name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install deps
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Lint
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint

      - name: Test
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test --ci --coverage --maxWorkers=2

      - name: build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
